server:
  port: ${API_WS_PORT}

spring:
  application:
    name: api-websocket
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDR}
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD_ADDR}
        port:
          8719
